import type { Metadata } from 'next'
import localFont from '@next/font/local'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Adriano Hardtke | Frontend Development',
  description: 'Generated by create next app',
}

const pecita = localFont({
  src: [
    {
      path: '../../public/fonts/Pecita.otf',
      weight: '400'
    },
  ],
  variable: '--font-pecita'
})


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body className={`${inter.className} ${pecita.variable} bg-primary text-dark`}>{children}</body>
    </html>
  )
}
